defaults:
  - _self_
  - experiment: null
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# Hydra config
hydra:
  run:
    dir: "${results_dir}/${dataset}/${now:%Y-%m-%d_%H-%M-%S}_${oc.select:tag,}"
  sweep:
    dir: "${hydra.run.dir}/${hydra.job.name}"
    subdir: "${hydra.run.dir}/${hydra.job.num}"
  job_logging:
    handlers:
      file:
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log  # Fixed in hydra-colorlog version 1.2.1

einet:
  S: 10
  I: 10
  D: 3
  R: 1
  layer_type: "linsum"
  structure: "top-down"

convpc:
  channels: [8, 16, 16, 16]
  order: "sum-prod"
  structure: "top-down"
  kernel_size: 2



# Default set of configurations.
data_dir: "${oc.env:DATA_DIR}/"
results_dir: "${oc.env:RESULTS_DIR}/${project_name}"
project_name: "simple-einet"
lr: 0.0005
batch_size: 64
n_bits: 8
num_workers: 16
temperature_leaves: 1.0
temperature_sums: 1.0
dropout: 0.0
min_sigma: 1e-2
max_sigma: 2.0
dry_run: False
seed: ???
log_interval: 10
classification: False
device: "cuda"
debug: False
gpu: 0
epochs: 10
load_and_eval: False
precision: "bf16-mixed"
group_tag: ???
tag: ???
wandb: False
swa: False
profiler: ???
dataset: ???
num_classes: 10
init_leaf_data: False
mixture: False
torch_compile: False
multivariate_cardinality: 2
dist: "normal"
model: "einet"  # Can be one of "einet" or "convpc"
